parameters:
    coreshop.dto.add_to_wishlist.class: 'CoreShop\Bundle\WishlistBundle\DTO\AddToWishlist'
    coreshop.session.wishlist: 'coreshop.wishlist'

imports:
    - { resource: services/wishlist.yml }
    - { resource: services/forms.yml }
    - { resource: services/context.yml }

services:
    _defaults:
        public: true

    CoreShop\Component\Wishlist\Manager\WishlistManagerInterface: '@CoreShop\Bundle\WishlistBundle\Manager\WishlistManager'
    CoreShop\Bundle\WishlistBundle\Manager\WishlistManager:
        arguments:
            - '@CoreShop\Component\Resource\Service\FolderCreationServiceInterface'
            - '@doctrine.dbal.default_connection'

    CoreShop\Component\Wishlist\Wishlist\WishlistItemResolver: ~

    CoreShop\Component\Wishlist\Wishlist\WishlistModifierInterface: '@CoreShop\Component\Wishlist\Wishlist\WishlistModifier'
    CoreShop\Component\Wishlist\Wishlist\WishlistModifier:
        arguments:
            - '@event_dispatcher'
            - '@CoreShop\Component\Wishlist\Wishlist\WishlistItemResolver'

    CoreShop\Component\Wishlist\Factory\WishlistItemFactory:
        decorates: coreshop.factory.wishlist_item
        decoration_priority: 256
        public: false
        arguments:
            - '@CoreShop\Component\Wishlist\Factory\WishlistItemFactory.inner'

    CoreShop\Component\Wishlist\Factory\WishlistFactory:
        decorates: coreshop.factory.wishlist
        decoration_priority: 256
        public: false
        arguments:
            - '@CoreShop\Component\Wishlist\Factory\WishlistFactory.inner'

    CoreShop\Bundle\WishlistBundle\Factory\AddToWishlistFactoryInterface: '@CoreShop\Bundle\WishlistBundle\Factory\AddToWishlistFactory'
    CoreShop\Bundle\WishlistBundle\Factory\AddToWishlistFactory:
        arguments:
            - '%coreshop.dto.add_to_wishlist.class%'