services:
  _defaults:
    public: true

  CoreShop\Component\Wishlist\Context\WishlistContext:
    arguments:
      - '@coreshop.factory.wishlist'
    tags:
      - { name: coreshop.context.wishlist, priority: -999 }

  CoreShop\Component\Wishlist\Context\WishlistContextInterface: '@CoreShop\Component\Wishlist\Context\CompositeWishlistContext'
  CoreShop\Component\Wishlist\Context\CompositeWishlistContext: ~

  CoreShop\Bundle\WishlistBundle\EventListener\SessionWishlistSubscriber:
    arguments:
      - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
      - '@CoreShop\Component\Wishlist\Context\WishlistContextInterface'
      - '%coreshop.session.wishlist%'
    tags:
      - { name: kernel.event_subscriber }
