parameters:
    coreshop.form.type.add_to_wishlist.validation_groups: [coreshop]
    coreshop.form.type.edit_wishlist.validation_groups: [coreshop]

services:
    CoreShop\Bundle\WishlistBundle\Form\Type\AddToWishlistType:
        arguments:
            - '%coreshop.dto.add_to_wishlist.class%'
            - '%coreshop.form.type.add_to_wishlist.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\WishlistBundle\Form\Type\WishlistType:
        arguments:
            - '%coreshop.model.wishlist.class%'
            - '%coreshop.form.type.wishlist.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\WishlistBundle\Form\Type\WishlistItemType:
        arguments:
            - '%coreshop.model.wishlist_item.class%'
            - '%coreshop.form.type.wishlist_item.validation_groups%'
        tags:
            - { name: form.type }
