parameters:
    coreshop.form.type.add_to_wishlist.validation_groups: [coreshop]
    coreshop.form.type.edit_wishlist.validation_groups: [coreshop]

services:
    CoreShop\Bundle\WishlistBundle\Form\Type\AddWishlistType:
        arguments:
            - '%coreshop.dto.add_to_wishlist.class%'
            - '%coreshop.form.type.add_to_wishlist.validation_groups%'
        tags:
            - { name: form.type }